// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAbvZaenOdLYmtKkvVaxrgn1BEANpMBts',
    appId: '1:149886594297:web:c409ebd09546805083c628',
    messagingSenderId: '149886594297',
    projectId: 'routine-app-project-1b021',
    authDomain: 'routine-app-project-1b021.firebaseapp.com',
    storageBucket: 'routine-app-project-1b021.firebasestorage.app',
    measurementId: 'G-3E45PXBMRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2GtZD5InbBG1VmautTh2_M88QfMj4zfA',
    appId: '1:149886594297:android:21798ff546d7f0ce83c628',
    messagingSenderId: '149886594297',
    projectId: 'routine-app-project-1b021',
    storageBucket: 'routine-app-project-1b021.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtDDz03QC-M7AsmuSvwBlMw_V0HgSfKNA',
    appId: '1:149886594297:ios:6b48f11a30edc2c883c628',
    messagingSenderId: '149886594297',
    projectId: 'routine-app-project-1b021',
    storageBucket: 'routine-app-project-1b021.firebasestorage.app',
    iosClientId: '149886594297-hdbe4lan75jn34c4unja9edopmd7p874.apps.googleusercontent.com',
    iosBundleId: 'com.example.routineapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtDDz03QC-M7AsmuSvwBlMw_V0HgSfKNA',
    appId: '1:149886594297:ios:6b48f11a30edc2c883c628',
    messagingSenderId: '149886594297',
    projectId: 'routine-app-project-1b021',
    storageBucket: 'routine-app-project-1b021.firebasestorage.app',
    iosClientId: '149886594297-hdbe4lan75jn34c4unja9edopmd7p874.apps.googleusercontent.com',
    iosBundleId: 'com.example.routineapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAbvZaenOdLYmtKkvVaxrgn1BEANpMBts',
    appId: '1:149886594297:web:a003212cd3a35e3483c628',
    messagingSenderId: '149886594297',
    projectId: 'routine-app-project-1b021',
    authDomain: 'routine-app-project-1b021.firebaseapp.com',
    storageBucket: 'routine-app-project-1b021.firebasestorage.app',
    measurementId: 'G-57YDV3BYWG',
  );
}
